[package]
name = "libsqlite3"
version = "0.1.0"
edition = "2021"

[lib]
name = "hellohq"
crate-type = ["lib", "staticlib", "cdylib"]

[dependencies]
libsqlite3-sys = { version = "0.23.2", features = ["bundled"] }

[build-dependencies]
cc = "1.0"

[dev-dependencies]
rusqlite = "0.26"
